
version: '2'
networks:
  database:
services:
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod
        networks:
          - database
    node-back:
      image: "node:8"
      user: "node"
      working_dir: /home/node/app
      environment:
        - NODE_ENV=production
        - PORT=3001
        - SENDER_USER=
        - SENDER_PASS=
        - SENDER_HOST=
        - ADMIN_MAIL=
      volumes:
        - ./spalert-back:/home/node/app
      ports:
        - 3001:3001
      command: "npm start"
      networks:
        - database
      depends_on:
        - mongodb
    node-front:
      image: "node:8"
      user: "node"
      working_dir: /home/node/app
      environment:
        - NODE_ENV=production
        - PORT=3000
      volumes:
        - ./spalert-front:/home/node/app
      ports:
        - 3000:3000
      command: "npm start"
